### ISSUE TITLE
Add support to redefine the configuration file

### ISSUE THREAD

**Issue by egorsmkv** [robertdebock/ansible-role-snort#1]
**Is your feature request related to a problem? Please describe.**
I am integration this Role with my graylog server and need to change the Snort config.

**Comment by robertdebock** [comment]
Cool, open to suggestions, tell me what modifications you'd like to make please.

Regards, Robert de Bock.

**Comment by egorsmkv** [comment]
I stuck with a problem "Where is the config file", so in order to solve this issue I added the argument in systemd unit file "-c ..../snort.conf" but then were issues with including rule sets that config uses. For solving the second problem I've found this repository - https://github.com/thereisnotime/Snort-Rules and after some fixes (the repo doesn't have blocklist/whitelist files a dynamicpreprocessor folder) I succeed to install it. 

I would like in order this all to be in this Role.

**Comment by robertdebock** [comment]
What I typically do for locations of files that change per distribution:

`vars/main.yml`:
```
_some_path:
  default: /etc/bla.conf
  RedHat: /etc/bla/bla.conf
  Debian: /etc/bla.conf.d/main.conf

some_path: "{{ _some_path[ansible_os_family] | default(_some_path['default']) }}"
```

Now some_path is available in the `tasks/main.yml` file or templates and will have a different value per distribution (based on `ansible_os_family`)

Hope that helps a bit, otherwise let me know more, we can even setup a call to get this addressed.
